crm/urls.py
from django.urls import path,re_path
from crm import views
urlpatterns = [
    path('createorder', views.createorder),
    path('createpurchaseorder', views.CreatePurchaseOrder.as_view()),
    path('getpms', views.CreatePurchaseOrder.addProduct),
    path('orderlistdetail', views.orderListDetail),
    path('getselect', views.getSelect),
    path('orderlist', views.Orderlist.as_view()),
    path('stocklist', views.stocklist),
    path('initdata', views.initdata),
    path('storage', views.Storage.as_view()),
    path('customer', views.Customer.as_view()),
    path('home',views.home),
    path('checkstock',views.Ajax.checkStock)
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
]

crm/models.py
from django.db import models
from django.db.models import Model

class Role(Model):
    name = models.CharField(max_length=32)

class User(Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    r = models.ForeignKey("Role",on_delete=models.CASCADE)

class Customer(Model):
    name = models.CharField(max_length=32)
    address = models.CharField(max_length=128)
    phone = models.CharField(max_length=11)
    addtime = models.DateField(auto_now_add=True)
    ct = models.ForeignKey("CustomerType",on_delete=models.CASCADE)
    cl = models.ForeignKey("CustomerLevel",on_delete=models.CASCADE)

class CustomerType(Model):
    """
    客户类型 1.个人 2.经销商
    """
    name = models.CharField(max_length=32)

class CustomerLevel(Model):
    """
    客户评级
    """
    name = models.CharField(max_length=32)

class CustomerOrder(Model):
    ordernum = models.BigIntegerField(primary_key=True)
    addtime = models.DateTimeField(auto_now_add=True)
    ordervalue = models.FloatField()
    arrears = models.FloatField()
    comment = models.CharField(max_length=256)
    ocn = models.ForeignKey("Customer",related_name = 'ocn',on_delete=models.CASCADE)
    on = models.ForeignKey("CustomerOrderType",on_delete=models.CASCADE)
    os = models.ForeignKey("OrderStatus",on_delete=models.CASCADE)

class OrderStatus(Model):
    """
    订单状态 1。完成，2。未完成
    """
    name = models.CharField(max_length=32)

class CustomerOrderType(Model):
    """
    订单类型 1。零售 2。批发 3。租赁 4.维修
    """
    name = models.CharField(max_length=32)

class OrderList(Model):
    order = models.ForeignKey("CustomerOrder",to_field="ordernum",on_delete=models.CASCADE)
    pm = models.ForeignKey("ProductModel",on_delete=models.CASCADE)
    productnum = models.IntegerField()

class ProductModel(Model):
    model = models.CharField(max_length=128)
    value = models.FloatField()
    fn = models.ForeignKey("Factory",on_delete=models.CASCADE)

class Factory(Model):
    name = models.CharField(max_length=64)

class Stock(Model):
    number = models.IntegerField()
    pm = models.ForeignKey("ProductModel",on_delete=models.CASCADE)

class PurchaseOrder(Model):
    ordernum = models.BigIntegerField(primary_key=True)
    addtime = models.DateTimeField(auto_now_add=True)
    ordervalue = models.FloatField()
    payment = models.FloatField()
    comment = models.CharField(max_length=256)
    fn = models.ForeignKey("Factory",on_delete=models.CASCADE)
    os = models.ForeignKey("OrderStatus",on_delete=models.CASCADE)

class PurchaseOrderList(Model):
    productnum = models.IntegerField(null=False)
    order = models.ForeignKey("PurchaseOrder",on_delete=models.CASCADE)
    pm = models.ForeignKey("ProductModel",on_delete=models.CASCADE)

def initData():
    role_data = {"name":"admin"}
    Role().objects.create(**role_data)

    user_data = {"name":"admin","password":"admin","r_id":1}
    User().objects.create(**user_data)

    li = [{"name":"经销商"},{"name":"个人"}]
    li = list(map(lambda x:CustomerType(**x),li))
    CustomerType.objects.bulk_create(li)

    li = [{"name":"优质"},{"name":"普通"},{"name":"失信"},{"name":"黑名单"}]
    li = list(map(lambda x:CustomerLevel(**x),li))
    CustomerLevel.objects.bulk_create(li)

    li = [{"name":"完成"},{"name":"未完成"}]
    li = list(map(lambda x:OrderStatus(**x),li))
    OrderStatus.objects.bulk_create(li)

    li = [{"name":"零售"},{"name":"批发"},{"name":"租赁"},{"name":"维修"}]
    li = list(map(lambda x:CustomerOrderType(**x),li))
    CustomerOrderType.objects.bulk_create(li)

crm/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.db.models import Q,F
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from crm import formvaild
from crm import models
import json
from django.views import View
import datetime,time

class DateEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj,datetime.datetime):
            return obj.strftime("%Y-%m-%d %H:%M:%S")
        else:
            return json.JSONEncoder.default(self,obj)
def home(request):
    return render(request,'crm/index.html',{'title':'index'})


class Conditions:
    @staticmethod
    def orderListQ(lst):
        con = Q()
        # lst = [{"key1":[]},{"key2":[]},{"key3":[]}]
        for i in lst:
            q = Q()
            if i[0] == "addtime" or i[0] == "ordervalue" or i[0] == "arrears":
                q.connector = "AND"
                q.children.append((i[0] + "__gte", i[1][0]))
                q.children.append((i[0] + "__lte", i[1][1]))
            else:
                q.connector = "OR"
                for j in i[1]:
                    q.children.append((i[0], j))
            con.add(q, "AND")
        return con
def initdata(req):
    resp = "ok"
    try:
        models.initData()
    except Exception as e:
        resp = e.__str__()
    return HttpResponse(resp)
def createorder(req):
    if req.method == "GET":
        form_obj = formvaild.CustomerOrderForm()
        order_list = formvaild.OrderListForm()
        factory_select = formvaild.FactorySelectForm()
        # time.strftime("%Y%m%d%H%M%S", time.localtime())
        return render(req, "crm/createorder.html", {"formObj": form_obj, "orderList": order_list,"factory_select":factory_select})
    formObj = formvaild.CustomerOrderForm(req.POST)
    resp = {"msg": "", "status": "ok", "err": formObj.errors}
    if formObj.is_valid():
        print(formObj.cleaned_data)
        orderNum = formObj.cleaned_data["ordernum"]
        orderList = json.loads(req.POST.get("orderList"))
        try:
            models.CustomerOrder.objects.create(**formObj.cleaned_data)
            li = list(map(lambda x: models.OrderList(order_id=orderNum, pm_id=x["pm_id"], productnum=x["productnum"]),
                          orderList))
            models.OrderList.objects.bulk_create(li)
            updateStock(orderList,"minus")
        except Exception as e:
            print(e)
            resp["msg"] = e.__str__()
            resp["status"] = "err"
    else:
        resp["status"] = "err"
    print(resp)
    return HttpResponse(json.dumps(resp))

def getSelect(req):
    if req.method == "POST":
        key = req.POST.get("key")
        if key == "ocn__name":
            data = models.Customer.objects.all().values("id", "name")
            return HttpResponse(json.dumps({"data":list(data)}))
        elif key == "on__name":
            data = models.CustomerOrderType.objects.all().values("id", "name")
            return HttpResponse(json.dumps({"data":list(data)}))
        elif key == "os__name":
            data = models.OrderStatus.objects.all().values("id", "name")
            return HttpResponse(json.dumps({"data":list(data)}))
        elif key == "ocn__ct__name":
            data = models.CustomerType.objects.all().values("id", "name")
            return HttpResponse(json.dumps({"data":list(data)}))

def orderListDetail(req):
    colsMap = {
        "pm__model": "产品型号",
        "pm__value": "产品单价",
        "productnum": "产品数量",
    }
    orderNum = req.POST.get("orderNum")
    print(req.POST)
    ret = models.OrderList.objects.filter(order_id=orderNum).select_related("pm_id").values("pm__model","pm__value","productnum")
    print(ret.query)
    print(list(ret))
    return HttpResponse(json.dumps({"data":list(ret),"tablehead":colsMap}))

class Orderlist(View):
    colsMap = {
        "ordernum": "订单号",
        "ordervalue": "订单总金额",
        "arrears": "订单欠款",
        "addtime":"下单时间",
        "ocn__name": "客户",
        "ocn__ct__name": "客户类型",
        "on__name": "订单类型",
        "os__name": "订单状态",
        "comment": "备注",
    }

    def get(self,req):
        return render(req,"crm/orderlist.html",{"selectOptions": self.colsMap})

    def paser(self,x):
        tmp = x[0]
        if "__name" in x[0]:
            tmp = x[0].replace("_name", "id")
        elif "comment" == x[0]:
            tmp = x[0]+"__contains"
        return (tmp,x[1])

    def post(self,req):
        obj = req.POST.get("data")
        pn = req.POST.get("pn")
        page_number = req.POST.get("page_number")
        obj = json.loads(obj)
        obj = list(map(lambda x:self.paser(x),obj.items()))
        ret = models.CustomerOrder.objects.filter(Conditions.orderListQ(obj)).select_related("on_id","os_id","ocn_id").values(
            *self.colsMap.keys())
        p = Paginator(list(ret), page_number)
        # print(ret.query)
        return HttpResponse(json.dumps({
            "data":p.page(pn).object_list,
            "page_range":[p.page_range.start,p.page_range.stop],
            "total_page":p.num_pages,
            "tablehead":self.colsMap},cls=DateEncoder))

def stocklist(req):
    if req.method == "GET":
        data = models.Stock.objects.all()
        return render(req, "crm/stocklist.html", {"data": data})

class Storage(View):
    def get(self,req):
        stock_list = formvaild.StorageForm()
        all = models.Stock.objects.select_related("pm_id","pm__fn_id").all().values("pm__model","number","pm__fn__name")
        print(list(all))
        return render(req, "crm/storage.html", {"stock_list": list(all)})

    def post(self,req):
        return HttpResponse("post")

class Customer(View):
    def get(self,req):
        formObj = formvaild.CustomerForm()
        return render(req, "crm/customer.html", {"formobj": formObj})

    def post(self,req):
        return HttpResponse("post")

class CreatePurchaseOrder(View):
    @staticmethod
    def addProduct(req):
        fn_id = req.POST.get("fn_id")
        ret=  models.ProductModel.objects.filter(fn_id=fn_id).values()
        return HttpResponse(json.dumps({"pms":list(ret)}))

    def get(self,req):
        form_obj = formvaild.PurchaseOrderForm()
        order_list = formvaild.OrderListForm()
        # return render(req, "crm/createpurchaseorder.html", {"formObj": form_obj, "orderList": order_list})        order_list = formvaild.OrderListForm()
        return render(req, "crm/createpurchaseorder.html", {"formObj": form_obj})

    def post(self,req):
        formObj = formvaild.PurchaseOrderForm(req.POST)
        resp = {"msg": "", "status": "ok", "err": formObj.errors}
        if formObj.is_valid():
            print(formObj.cleaned_data)
            orderNum = formObj.cleaned_data["ordernum"]
            orderList = json.loads(req.POST.get("orderList"))
            try:
                models.PurchaseOrder.objects.create(**formObj.cleaned_data)
                li = list(
                    map(lambda x: models.PurchaseOrderList(order_id=orderNum, pm_id=x["pm_id"], productnum=x["productnum"]),
                        orderList))
                models.PurchaseOrderList.objects.bulk_create(li)
                updateStock(orderList,"add")
            except Exception as e:
                print(e)
                resp["msg"] = e.__str__()
                resp["status"] = "err"
        else:
            resp["status"] = "err"
        print(resp)
        return HttpResponse(json.dumps(resp))

def updateStock(pmlist,opt):
    for one in pmlist:
        pm_id = one["pm_id"]
        number = one["productnum"]
        o = models.Stock.objects.filter(pm_id=pm_id)
        if o.exists():
            if opt == "add":
                o.update(number=F("number") + number)
            else:
                o.update(number=F("number") - number)
        else:
            models.Stock.objects.create(pm_id=pm_id, number=number)

class Ajax:
    @staticmethod
    def checkStock(req):
        data = req.POST.get("data")
        li = json.loads(data)["list"]
        dic = {}
        for i in li:
            pm_id = i["pm_id"]
            number = int(i["productnum"])
            if dic.get(pm_id):
                dic[pm_id] = dic[pm_id] + number
            else:
                dic[pm_id] = number
        ret = {"msg": "","status":"ok"}
        for i,n in dic.items():
            o = models.Stock.objects.filter(pm_id=i).values("number","pm__model").first()
            if o["number"] < n:
                ret["status"] = "err"
                ret["msg"]+="%s 库存数量%d 少于订单数量%s"%(o["pm__model"],o["number"],dic[i])
        print(ret)
        return HttpResponse(json.dumps(ret))

templates/crm/createorder.html
{% extends 'base.html' %}

{% block content %}
    {% include "contenthead.html"  with title="客户订单创建" %}
    <div class="row">
        <div class="col-7">
            <div>
                {{ factory_select.fn.label }}{{ factory_select.fn }}
                <button type="button" class="btn btn-sm btn-primary" onclick="addProduct()">添加型号</button>
            </div>
            <h6>订单列表</h6>
            <table border="1" id="listTb" class="table table-sm table-bordered">
                <thead>
                <tr>
                    <th>型号</th>
                    <th>数量</th>
                    <th>单价</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody id="listTbtbody">
                </tbody>
            </table>
        </div>
        <div class="col-5">
            <div class="row">
                <div class="col">
                    <h4>创建订单</h4>
                </div>
                <span></span>
                <div class="col-4">
                    <button type="button" class="btn btn-sm btn-success" onclick="AjaxPost()">提交数据</button>

                </div>
            </div>

            <form action="createorder" method="post" id="f1">
                {% csrf_token %}
                <p>{{ formObj.ordernum.label }}{{ formObj.ordernum }}{{ formObj.errors.ordernum.0 }}</p>
                <p>{{ formObj.ocn_id.label }}{{ formObj.ocn_id }}{{ formObj.errors.ocn_id.0 }}</p>
                <p>{{ formObj.ordervalue.label }}{{ formObj.ordervalue }}{{ formObj.errors.ordervalue.0 }}</p>
                <p>{{ formObj.arrears.label }}{{ formObj.arrears }}{{ formObj.errors.arrears.0 }}</p>
                <p>{{ formObj.on_id.label }}{{ formObj.on_id }}{{ formObj.errors.on_id.0 }}</p>
                <p>{{ formObj.os_id.label }}{{ formObj.os_id }}{{ formObj.errors.os_id.0 }}</p>
                <p>{{ formObj.comment.label }}{{ formObj.comment }}{{ formObj.errors.comment.0 }}</p>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function (){
            $("#id_ordernum").val(getIntTime())
        });

        function deleteProduct(dom) {
            $(dom).parent().parent().remove();
            calcordervalue()
        }

        $('#listTbtbody').on('input propertychange', function () {
            calcordervalue()
        })

        function calcordervalue() {
            let tbody = $('#listTbtbody')
            let total = 0
            for (let i of tbody.children()) {
                let number = $(i).children()[1].firstChild.value
                let value = $(i).children()[2].firstChild.value
                total += number * value
            }
            $('#id_ordervalue').val(total)
        }

        function addProduct() {
            let listTbtbody = $('#listTbtbody')
            let fn_id = $("#id_fn").val()
            $.ajax({
                url: "/crm/getpms",
                method: "POST",
                data: {"fn_id": fn_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success: function (arg) {
                    let res = JSON.parse(arg)
                    console.log(arg)
                    let listTbtbody = $("#listTbtbody")
                    let select = '<select  class="form-control" name="pms">'
                    for (let i of res["pms"]) {
                        select += `<option value="${i["id"]}">${i["model"]}</option>`
                    }
                    listTbtbody.append(
                        `<tr><td>${select}</select></td>
    <td><input class="form-control number" style="width: 70px" type="number" value=1></td>
    <td><input class="form-control value" style="width: 70%" type="number" value=0></td>
    <td><button class="btn btn-sm btn-warning" onclick="deleteProduct(this)">删除</button></td></tr>`
                    )
                },
            })
        }

        function getTbList() {
            let tbody = $('#listTbtbody')
            let list = []
            for (let i  of tbody.children()) {
                let number = $(i).children()[1].firstChild.value
                let pm_id = $(i).children()[0].firstChild.value
                list.push({"productnum": number, "pm_id": pm_id})
            }
            return list
        }

        function clearErr() {
            let e = $(".err")
            for (let i = 0; i < e.length; i++) {
                e[i].remove()
            }
        }

        function checkStock(list) {
            let url = '/crm/checkstock'
            obj = {"list":list}
            let formdata = new FormData
            formdata.append("csrfmiddlewaretoken",'{{ csrf_token }}')
            formdata.append("data",JSON.stringify(obj))
            fetch(url , {
              method: 'POST',
              body:formdata,
            })
                .then(res => res.json())
                .then(function (json) {
                    if(json.status==="ok"){
                        toastr.success("成功!")
                        return true
                    }else {
                        toastr.error("失败了：" + json.msg)
                        return false
                    }
                })
                .catch((e)=>toastr.error(e))
        }

        function AjaxPost() {
            clearErr()
            let data = $("#f1").serialize()
            let list = getTbList()
            if (list.length===0){
                toastr.warning("提醒：产品列表不能为空")
                return
            }
            if (!checkStock(list)){return}
            data += "&orderList=" + JSON.stringify(getTbList())
            $.ajax({
                url: "/crm/createorder",
                method: "POST",
                data: data,
                success: function (arg) {
                    let m = JSON.parse(arg)
                    if (m.status === 'err') {
                        for (let i in m.err) {
                            let tmp = m.err[i]
                            $(`input[name|=${i}`).after(`<span class="err">${tmp}</span>`)
                        }
                        toastr.error("失败了：" + m.msg)
                    } else {
                        toastr.success("采购订单创建成功!")
                    }
                },
            })
        }
    </script>
{% endblock script %}

templates/crm/createpurchaseorder.html
{% extends 'base.html' %}

{% block content %}

    {% include "contenthead.html"  with title="采购订单创建" %}
    <div class="row">
        <div class="col-7">
            <div>
                <button type="button" class="btn btn-sm btn-primary" onclick="addProduct()">添加型号</button>
            </div>
            <h6>订单列表</h6>
            <table id="listTb" class="table table-sm table-bordered">
                <thead>
                <tr>
                    <th>型号</th>
                    <th>数量</th>
                    <th>单价</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody id="listTbtbody">
                </tbody>
            </table>
        </div>
        <div class="col-5">
            <div class="row">
                <div class="col">
                    <h4>创建订单</h4>
                </div>
                <span></span>
                <div class="col-4">
                    <button type="button" class="btn btn-sm btn-success" onclick="AjaxPost()">提交数据</button>

                </div>
            </div>
            <form action="createorder" method="post" id="f1">
                {% csrf_token %}
                <p>{{ formObj.ordernum.label }}{{ formObj.ordernum }}{{ formObj.errors.ordernum.0 }}</p>
                <p>{{ formObj.ordervalue.label }}{{ formObj.ordervalue }}{{ formObj.errors.ordervalue.0 }}</p>
                <p>{{ formObj.fn_id.label }}{{ formObj.fn_id }}{{ formObj.errors.fn_id.0 }}</p>
                <p>{{ formObj.os_id.label }}{{ formObj.os_id }}{{ formObj.errors.os_id.0 }}</p>
                <p>{{ formObj.payment.label }}{{ formObj.payment }}{{ formObj.errors.payment.0 }}</p>
                <p>{{ formObj.comment.label }}{{ formObj.comment }}{{ formObj.errors.comment.0 }}</p>
            </form>
        </div>

    </div>


{% endblock %}
{% block script %}
    <script>
        $(document).ready(function (){
            $("#id_ordernum").val(getIntTime())
        });
        function deleteProduct(dom) {
            $(dom).parent().parent().remove();
            calcordervalue()
        }
        $("#id_fn_id").on("change", function () {
            $('#listTbtbody').children().remove()
            $('#id_ordervalue').val(0)
        })
        $('#listTbtbody').on('input propertychange', function () {
            calcordervalue()
        })
        function calcordervalue() {
            let tbody = $('#listTbtbody')
            let total = 0
            for (let i of tbody.children()) {
                let number = $(i).children()[1].firstChild.value
                let value = $(i).children()[2].firstChild.value
                total += number * value
            }
            $('#id_ordervalue').val(total)
        }

        function addProduct() {
            let fn_id = $("[name='fn_id']").val()
            $.ajax({
                url: "/crm/getpms",
                method: "POST",
                data: {"fn_id": fn_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success: function (arg) {
                    let res = JSON.parse(arg)
                    console.log(arg)
                    let listTbtbody = $("#listTbtbody")
                    let select = '<select  class="form-control" name="pms">'
                    for (let i of res["pms"]) {
                        select += `<option value="${i["id"]}">${i["model"]}</option>`
                    }
                    listTbtbody.append(
                        `<tr><td>${select}</select></td>
<td><input class="form-control number" style="width: 70px" type="number" value=1></td>
<td><input class="form-control value" style="width: 70%" type="number" value=0></td>
<td><button class="btn btn-sm btn-warning" onclick="deleteProduct(this)">删除</button></td></tr>`
                    )
                },
            })
        }

        function getTbList() {
            let tbody = $('#listTbtbody')
            let list = []
            for (let i  of tbody.children()) {
                let number = $(i).children()[1].firstChild.value
                let pm_id = $(i).children()[0].firstChild.value
                list.push({"productnum": number, "pm_id": pm_id})
            }
            return list
        }

        function clearErr() {
            let e = $(".err")
            for (let i = 0; i < e.length; i++) {
                e[i].remove()
            }
        }

        function AjaxPost() {
            clearErr()
            let data = $("#f1").serialize()
            let list = getTbList()
            if (list.length===0){
                toastr.warning("提醒：产品列表不能为空")
                return
            }
            data += "&orderList=" + JSON.stringify(list)
            $.ajax({
                url: "/crm/createpurchaseorder",
                method: "POST",
                data: data,
                success: function (arg) {
                    let m = JSON.parse(arg)
                    if (m.status === 'err') {
                        for (let i in m.err) {
                            let tmp = m.err[i]
                            $(`input[name|=${i}`).after(`<span class="err">${tmp}</span>`)
                        }
                        toastr.error("失败了：" + m.msg)

                    } else {
                        toastr.success("采购订单创建成功!")

                    }
                },
            })
        }
    </script>
{% endblock script %}

templates/crm/customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>客户</h1>
    <form action="customer" method="post" id="f1">
        {% csrf_token %}
        <p>{{ formobj.name.label }}{{ formobj.name}}{{ formobj.errors.name.0 }}</p>
        <p>{{ formobj.address.label }}{{ formobj.address}}{{ formobj.errors.address.0 }}</p>
        <p>{{ formobj.phone.label }}{{ formobj.phone}}{{ formobj.errors.phone.0 }}</p>
        <p>{{ formobj.ct_id.label }}{{ formobj.ct_id}}{{ formobj.errors.ct_id.0 }}</p>
        <p>{{ formobj.cl_id.label }}{{ formobj.cl_id}}{{ formobj.errors.cl_id.0 }}</p>

        <p><input type="submit" value="submit">
            </p>
    </form>
</body>
</html>

templates/crm/motal.html
<div id="mymodal" class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">{{title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalbody">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
{#        <button type="button" class="btn btn-primary">Save changes</button>#}
      </div>
    </div>
  </div>
</div>

templates/crm/stocklist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table border="1">
        <thead class="thead-light">
        <tr>
            <th>型号</th>
            <th>厂家</th>
            <th>单价</th>
            <th>数量</th>
        </tr>
        </thead>
        <tbody>
        {% for datum in data %}
            <tr>
                <td>{{ datum.pm.model }}</td>
                <td>{{ datum.pm.fn.name }}</td>
                <td>{{ datum.pm.value }}</td>
                <td>{{ datum.number }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/crm/storage.html
{% extends "base.html" %}
{% block content %}
    {% include "contenthead.html" with title="库存管理" %}
    <table id="listTb" class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
              <tr>
                <th>型号</th>
                <th>数量</th>
                <th>厂家</th>
              </tr>
        </thead>
        <tbody>
        {% for stock in stock_list %}
              <tr id="tr">
                <td>{{ stock.pm__model }}</td>
                <td>{{ stock.number }}</td>
                <td>{{ stock.pm__fn__name }}</td>
              </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script %}
<script>

</script>
{% endblock script %}